### ISSUE TITLE
[Suggestion] Allow for font as command line option

### ISSUE THREAD

**Issue by gamesbook** [will8211/unimatrix#17]
Is there any possibility that the program could be extended to allow for the user to specify a font?

I tried downloading this Klingon TTF font (http://www.kasper-online.de/en/docs/startrek/klingon.zip) but it did not work; if there was a way to specify a font, then I assume it would?

**Comment by will8211** [comment]
I don't think it would be possible to do this, as the font is set by the terminal emulator...

**Comment by Khoyo** [comment]
If your terminal emulator supports fallback fonts through fontconfig, you may be able to setup your font as a fallback for the Klingon unicode characters. But the programs running in a terminal don't have any way of specifying the used font (which is why projects likes vim airline have to use patched fonts, etc)

**Comment by will8211** [comment]
@Khoyo, thanks for the pointer about fontconfig, I mentioned it in the reader for the Klingon fonts. 

@gamesbook, have a look at the font files and instructions in the new Klingon folder.

I'll close the issue, since it seems not doable.
